name: Sphinx build

on:
  workflow_dispatch:
    inputs:
      doc_format:
        description: 'Extension to parse docstrings'
        required: true
        default: 'numpydoc'
        type: choice
        options:
          - numpydoc
          - napoleon
  push:
    branches:
      - main

jobs:
  build-deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: yuanx749/auto-sphinx-page-action@main
        with:
          sourcedir: docs
          requirements: docs/requirements.txt
        env:
          doc_format: ${{ inputs.doc_format }}
